services:
  postgres:
    image: postgres:17
    container_name: bha-pg
    shm_size: 256mb
    environment:
      POSTGRES_USER: merry
      POSTGRES_PASSWORD: secondbreakfast
      POSTGRES_DB: bha_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U merry -d bha_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin_service:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    volumes:
      - ~/pgadmin-data:/var/lib/pgadmin