services:
  postgres:
    image: postgres:16
    container_name: bha-pg
    environment:
      POSTGRES_USER: merry
      POSTGRES_PASSWORD: secondbreakfast
      POSTGRES_DB: bha_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U merry -d bha_db"]
      interval: 5s
      timeout: 5s
      retries: 5