services:
  postgres:
    image: postgres:17
    container_name: bha-pg
    shm_size: 256mb
    environment:
      POSTGRES_USER: merry
      POSTGRES_PASSWORD: secondbreakfast
      POSTGRES_DB: bha_db
    ports:
      - "5433:5432"
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U merry -d bha_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin_service:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    volumes:
      - ~/pgadmin-data:/var/lib/pgadmin
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: bha-backend
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=merry
      - DB_PASSWORD=secondbreakfast
      - DB_NAME=bha_db
      - DB_PORT=5432
      - JWT_SECRET=yourjwtsecret
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: bha-frontend
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
